cookie:
  expiry_days: 0
  key: ldshnlakjx89o7ouqenuoy8234 # Must be a string
  name: anmintegrity
credentials:
  usernames:
    Admin:
      email: admin@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Admin
      last_name: .
      logged_in: False # Will be managed automatically
      password: anmintegrity # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    # rbriggs:
    #   email: rbriggs@gmail.com
    #   failed_login_attempts: 0 # Will be managed automatically
    #   first_name: Rebecca
    #   last_name: Briggs
    #   logged_in: False # Will be managed automatically
    #   password: def # Will be hashed automatically
    #   roles: # Optional
    #   - viewer
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  microsoft: # Follow instructions: https://learn.microsoft.com/en-us/graph/auth-register-app-v2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
    tenant_id: # To be filled
# pre-authorized: # Optional
#   emails:
#   - melsby@gmail.com